server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /promtail_positions/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: syslog_collect
    syslog:
      listen_address: 0.0.0.0:4445
      use_incoming_timestamp: true
      labels:
        service_name: syslog
    relabel_configs:
      - target_label: xhostname
        source_labels: ["__syslog_connection_hostname"]
      - target_label: xseverity
        source_labels: ["__syslog_message_severity"]
      - target_label: xscrapedhostname
        source_labels: ["__syslog_message_hostname"]
